#!/usr/bin/env python3
from __future__ import annotations

import argparse
import logging
import os
import re
import subprocess
import sys
import shutil
from contextlib import contextmanager
from typing import Callable, Optional

# begin constants definition

VERSION = '3.5.2'

# Note: Do NOT remove this in cleanup!
CACHE_FILE_PATH = '/var/cache/greenwithenvy/cache.json'

BLACKLIST_PATH = '/etc/modprobe.d/blacklist-nvidia.conf'

BLACKLIST_CONTENT = '''# Automatically generated by GreenWithEnvy

blacklist nouveau
blacklist nova_core
blacklist nova_drm
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_uvm
blacklist nvidia_modeset
blacklist nvidia_current
blacklist nvidia_current_drm
blacklist nvidia_current_uvm
blacklist nvidia_current_modeset
blacklist i2c_nvidia_gpu
alias nouveau off
alias nova_core off
alias nova_drm off
alias nvidia off
alias nvidia_drm off
alias nvidia_uvm off
alias nvidia_modeset off
alias nvidia_current off
alias nvidia_current_drm off
alias nvidia_current_uvm off
alias nvidia_current_modeset off
alias i2c_nvidia_gpu off
'''

UDEV_INTEGRATED_PATH = '/etc/udev/rules.d/50-remove-nvidia.rules'

UDEV_INTEGRATED = '''# Automatically generated by GreenWithEnvy

# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA VGA/3D controller devices
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x03[0-9]*", ATTR{power/control}="auto", ATTR{remove}="1"
'''

UDEV_PM_PATH = '/etc/udev/rules.d/80-nvidia-pm.rules'

UDEV_PM_CONTENT = '''# Automatically generated by GreenWithEnvy

# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{remove}="1"

# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{remove}="1"

# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{remove}="1"

# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"

# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
'''

XORG_PATH = '/etc/X11/xorg.conf'

XORG_INTEL = '''# Automatically generated by GreenWithEnvy

Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "{}"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection
'''

XORG_AMD = '''# Automatically generated by GreenWithEnvy

Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "amdgpu"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "{}"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "amdgpu"
    Driver "amdgpu"
EndSection

Section "Screen"
    Identifier "amd"
    Device "amdgpu"
EndSection
'''

EXTRA_XORG_PATH = '/etc/X11/xorg.conf.d/10-nvidia.conf'

EXTRA_XORG_CONTENT = '''# Automatically generated by GreenWithEnvy

Section "OutputClass"
    Identifier "nvidia"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
'''

FORCE_COMP = '    Option "ForceCompositionPipeline" "true"\n'

COOLBITS = '    Option "Coolbits" "{}"\n'

MODESET_PATH = '/etc/modprobe.d/nvidia.conf'

MODESET_CONTENT = '''# Automatically generated by GreenWithEnvy

options nvidia-drm modeset=1
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
'''

MODESET_CURRENT_CONTENT = '''# Automatically generated by GreenWithEnvy

options nvidia-current-drm modeset=1
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
'''

MODESET_RTD3 = '''# Automatically generated by GreenWithEnvy

options nvidia-drm modeset=1
options nvidia "NVreg_DynamicPowerManagement=0x0{}"
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
'''

MODESET_CURRENT_RTD3 = '''# Automatically generated by GreenWithEnvy

options nvidia-current-drm modeset=1
options nvidia-current "NVreg_DynamicPowerManagement=0x0{}"
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
'''

SDDM_XSETUP_PATH = '/usr/share/sddm/scripts/Xsetup'

SDDM_XSETUP_CONTENT = '''#!/bin/sh
# Xsetup - run as root before the login dialog appears

'''

LIGHTDM_SCRIPT_PATH = '/etc/lightdm/nvidia.sh'

LIGHTDM_CONFIG_PATH = '/etc/lightdm/lightdm.conf.d/20-nvidia.conf'

LIGHTDM_CONFIG_CONTENT = '''# Automatically generated by GreenWithEnvy

[Seat:*]
display-setup-script=/etc/lightdm/nvidia.sh
'''

NVIDIA_XRANDR_SCRIPT = '''#!/bin/sh
# Automatically generated by GreenWithEnvy

current=""

xrandr --setprovideroutputsource "{}" NVIDIA-0
xrandr --auto

for next in $(xrandr --listmonitors | grep -E " *[0-9]+:.*" | cut -d" " -f6); do
  [ -z "$current" ] && current=$next && continue
  xrandr --output "$current" --auto --output "$next" --auto --right-of "$current"
  current=$next
done
'''

SUPPORTED_MODES = ['integrated', 'hybrid', 'nvidia']
SUPPORTED_DISPLAY_MANAGERS = ['gdm', 'gdm3', 'sddm', 'lightdm']
RTD3_MODES = [0, 1, 2, 3]

# PCI vendor IDs for reliable GPU detection
_VENDOR_NVIDIA = '10de'
_VENDOR_INTEL = '8086'
_VENDOR_AMD = '1002'
_VENDOR_QUALCOMM = '17cb'

# PCI class codes for graphics devices
_GPU_CLASS_CODES = ('0300', '0302', '0380')

# Mapping of PCI vendor IDs to iGPU vendor names
_IGPU_VENDOR_MAP: dict[str, str] = {
    _VENDOR_INTEL: 'intel',
    _VENDOR_AMD: 'amd',
    _VENDOR_QUALCOMM: 'qualcomm',
}

# Regex for parsing lspci -Dnn output lines
# Example: "0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA107M [GeForce RTX 3050 Ti Mobile] [10de:25a0] (rev a1)"
_LSPCI_PATTERN = re.compile(
    r'^(?P<domain>[0-9a-fA-F]{4}):(?P<slot>[0-9a-fA-F]{2}:[0-9a-fA-F]{2}\.[0-9a-fA-F])'
    r'\s+(?P<class_name>.+?)\s+\[(?P<class_id>[0-9a-fA-F]{4})\]:\s+'
    r'(?P<description>.+?)\s+\[(?P<vendor_id>[0-9a-fA-F]{4}):(?P<device_id>[0-9a-fA-F]{4})\]'
)

# end constants definition


def _run_cmd(command: list[str], error_msg: str = "Command failed") -> int:
    """Run a subprocess, suppressing output unless verbose mode is enabled."""
    if logging.getLogger().level == logging.DEBUG:
        result = subprocess.run(command)
    else:
        result = subprocess.run(
            command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return result.returncode


def _get_gpu_names() -> tuple[Optional[str], Optional[str]]:
    """Return (igpu_name, dgpu_name) human-readable model names from detected GPUs."""
    devices = _parse_gpu_devices()
    igpu_name = None
    dgpu_name = None
    for d in devices:
        if d['vendor_id'] == _VENDOR_NVIDIA:
            if dgpu_name is None:
                dgpu_name = d['description']
        else:
            if igpu_name is None:
                igpu_name = d['description']
    return igpu_name, dgpu_name


def _print_gpu_status(mode: str, igpu_name: Optional[str], dgpu_name: Optional[str]) -> None:
    """Print a summary of which GPUs are active/inactive for a given mode."""
    igpu_label = igpu_name or 'Integrated GPU'
    dgpu_label = dgpu_name or 'Nvidia dGPU'

    if mode == 'integrated':
        print(f"  ✓ ACTIVE:   {igpu_label}")
        print(f"  ✗ DISABLED: {dgpu_label}")
    elif mode == 'hybrid':
        print(f"  ✓ ACTIVE:   {igpu_label} (primary)")
        print(f"  ✓ ACTIVE:   {dgpu_label} (on-demand)")
    elif mode == 'nvidia':
        print(f"  ✗ INACTIVE: {igpu_label}")
        print(f"  ✓ ACTIVE:   {dgpu_label} (primary)")


def _manage_persistenced(action: str) -> None:
    """Enable or disable the nvidia-persistenced systemd service."""
    returncode = _run_cmd(
        ["systemctl", action, "nvidia-persistenced.service"])
    if returncode == 0:
        print(f'Successfully {action}d nvidia-persistenced.service')
    else:
        logging.error(
            f"An error occurred while running 'systemctl {action}' for nvidia-persistenced")


def _switch_integrated(use_nvidia_current: bool) -> None:
    """Switch to integrated graphics mode (iGPU only, dGPU powered off)."""
    _manage_persistenced("disable")
    cleanup()

    # blacklist all nouveau, nova and Nvidia modules
    create_file(BLACKLIST_PATH, BLACKLIST_CONTENT)

    # power off the Nvidia GPU with udev rules
    create_file(UDEV_INTEGRATED_PATH, UDEV_INTEGRATED)

    rebuild_initramfs()


def _switch_hybrid(
    rtd3_value: Optional[int],
    use_nvidia_current: bool,
) -> None:
    """Switch to hybrid graphics mode (PRIME offloading with optional RTD3)."""
    print(
        f"Enable PCI-Express Runtime D3 (RTD3) Power Management: {rtd3_value or False}")
    cleanup()
    _manage_persistenced("enable")

    if rtd3_value is None:
        if use_nvidia_current:
            create_file(MODESET_PATH, MODESET_CURRENT_CONTENT)
        else:
            create_file(MODESET_PATH, MODESET_CONTENT)
    else:
        # setup rtd3
        if use_nvidia_current:
            create_file(
                MODESET_PATH, MODESET_CURRENT_RTD3.format(rtd3_value))
        else:
            create_file(MODESET_PATH, MODESET_RTD3.format(rtd3_value))
        create_file(UDEV_PM_PATH, UDEV_PM_CONTENT)

    rebuild_initramfs()


def _switch_nvidia(
    user_display_manager: Optional[str],
    enable_force_comp: bool,
    coolbits_value: Optional[int],
    use_nvidia_current: bool,
    pci_bus_getter: Optional[Callable[[], str]] = None,
) -> None:
    """Switch to dedicated Nvidia graphics mode (dGPU only)."""
    print(f"Enable ForceCompositionPipeline: {enable_force_comp}")
    print(f"Enable Coolbits: {coolbits_value or False}")

    _manage_persistenced("enable")
    cleanup()

    # get the Nvidia dGPU PCI bus
    nvidia_gpu_pci_bus = (pci_bus_getter or get_nvidia_gpu_pci_bus)()

    # get iGPU vendor
    igpu_vendor = get_igpu_vendor()

    # create the X.org config
    if igpu_vendor == 'intel':
        create_file(XORG_PATH, XORG_INTEL.format(nvidia_gpu_pci_bus))
    elif igpu_vendor == 'amd':
        create_file(XORG_PATH, XORG_AMD.format(nvidia_gpu_pci_bus))
    else:
        logging.warning(
            f"No Xorg configuration template for iGPU vendor '{igpu_vendor}'. "
            f"Nvidia mode may not work correctly without a manual xorg.conf.")

    # enable modeset for Nvidia driver
    if use_nvidia_current:
        create_file(MODESET_PATH, MODESET_CURRENT_CONTENT)
    else:
        create_file(MODESET_PATH, MODESET_CONTENT)

    # extra Xorg config
    if enable_force_comp and coolbits_value is not None:
        create_file(EXTRA_XORG_PATH, EXTRA_XORG_CONTENT + FORCE_COMP +
                    COOLBITS.format(coolbits_value) + 'EndSection\n')
    elif enable_force_comp:
        create_file(EXTRA_XORG_PATH, EXTRA_XORG_CONTENT +
                    FORCE_COMP + 'EndSection\n')
    elif coolbits_value is not None:
        create_file(EXTRA_XORG_PATH, EXTRA_XORG_CONTENT +
                    COOLBITS.format(coolbits_value) + 'EndSection\n')

    # try to detect the display manager if not provided
    if user_display_manager is None:
        display_manager = get_display_manager()
    else:
        display_manager = user_display_manager

    # warn if the display manager is not supported
    if display_manager is not None and display_manager not in SUPPORTED_DISPLAY_MANAGERS:
        logging.warning(
            f"Display manager '{display_manager}' is not supported by GreenWithEnvy. "
            f"Supported display managers: {', '.join(SUPPORTED_DISPLAY_MANAGERS)}. "
            f"Nvidia mode may result in a black screen without manual xrandr configuration.")

    # only sddm and lightdm require further config
    if display_manager == 'sddm':
        # backup Xsetup
        if os.path.exists(SDDM_XSETUP_PATH):
            logging.info("Creating Xsetup backup")
            with open(SDDM_XSETUP_PATH, mode='r', encoding='utf-8') as f:
                create_file(SDDM_XSETUP_PATH+'.bak', f.read())
        create_file(SDDM_XSETUP_PATH,
                    generate_xrandr_script(igpu_vendor), True)
    elif display_manager == 'lightdm':
        create_file(LIGHTDM_SCRIPT_PATH,
                    generate_xrandr_script(igpu_vendor), True)
        create_file(LIGHTDM_CONFIG_PATH, LIGHTDM_CONFIG_CONTENT)

    rebuild_initramfs()


def graphics_mode_switcher(
    graphics_mode: str,
    user_display_manager: Optional[str],
    enable_force_comp: bool,
    coolbits_value: Optional[int],
    rtd3_value: Optional[int],
    use_nvidia_current: bool,
    pci_bus_getter: Optional[Callable[[], str]] = None,
) -> None:
    """Switch between integrated, hybrid, and nvidia graphics modes."""
    current_mode = get_current_mode()
    igpu_name, dgpu_name = _get_gpu_names()

    print(f"Switching graphics mode: {current_mode} → {graphics_mode}")
    print()
    print("Before:")
    _print_gpu_status(current_mode, igpu_name, dgpu_name)
    print()

    if graphics_mode == 'integrated':
        _switch_integrated(use_nvidia_current)
    elif graphics_mode == 'hybrid':
        _switch_hybrid(rtd3_value, use_nvidia_current)
    elif graphics_mode == 'nvidia':
        _switch_nvidia(
            user_display_manager, enable_force_comp,
            coolbits_value, use_nvidia_current, pci_bus_getter,
        )

    print()
    print("After (takes effect on next reboot):")
    _print_gpu_status(graphics_mode, igpu_name, dgpu_name)
    print()
    print('Operation completed successfully')
    print('Please reboot your computer for changes to take effect!')


def cleanup() -> None:
    """Remove all GreenWithEnvy-generated config files and restore backups."""
    # define list of files to remove
    to_remove = [
        BLACKLIST_PATH,
        UDEV_INTEGRATED_PATH,
        UDEV_PM_PATH,
        XORG_PATH,
        EXTRA_XORG_PATH,
        MODESET_PATH,
        LIGHTDM_SCRIPT_PATH,
        LIGHTDM_CONFIG_PATH,
        # legacy files
        '/etc/X11/xorg.conf.d/90-nvidia.conf',
        '/lib/udev/rules.d/50-remove-nvidia.rules',
        '/lib/udev/rules.d/80-nvidia-pm.rules'
    ]

    # remove each file in the list
    for file_path in to_remove:
        try:
            if os.path.exists(file_path):
                os.remove(file_path)
                logging.info(f"Removed file {file_path}")
        except OSError as e:
            # ignore ENOENT race and EROFS on immutable distros (e.g. Fedora Kinoite)
            if e.errno not in (2, 30):
                logging.error(f"Failed to remove file '{file_path}': {e}")
            elif e.errno == 30:
                logging.debug(
                    f"Skipping read-only file '{file_path}' (immutable filesystem)")

    # restore Xsetup backup if found
    backup_path = SDDM_XSETUP_PATH + ".bak"
    if os.path.exists(backup_path):
        logging.info("Restoring Xsetup backup")
        with open(backup_path, mode="r", encoding="utf-8") as f:
            create_file(SDDM_XSETUP_PATH, f.read())
        # remove backup
        os.remove(backup_path)
        logging.info(f"Removed file {backup_path}")


def _parse_gpu_devices() -> list[dict]:
    """Parse lspci -Dnn output and return all graphics devices as structured dicts."""
    try:
        lspci_output = subprocess.check_output(
            ['lspci', '-Dnn']).decode('utf-8')
    except (subprocess.CalledProcessError, FileNotFoundError):
        logging.error("Failed to run 'lspci -Dnn'. Is pciutils installed?")
        return []

    devices = []
    for line in lspci_output.splitlines():
        match = _LSPCI_PATTERN.match(line)
        if not match:
            continue

        class_id = match.group('class_id').lower()
        if class_id not in _GPU_CLASS_CODES:
            continue

        device = {
            'domain': match.group('domain'),
            'slot': match.group('slot'),
            'class_name': match.group('class_name').strip(),
            'class_id': class_id,
            'description': match.group('description').strip(),
            'vendor_id': match.group('vendor_id').lower(),
            'device_id': match.group('device_id').lower(),
        }
        devices.append(device)
        logging.info(
            f"Detected GPU: [{device['vendor_id']}:{device['device_id']}] "
            f"{device['description']} at {device['domain']}:{device['slot']} "
            f"(class {device['class_id']}: {device['class_name']})")

    return devices


def get_nvidia_gpu_pci_bus() -> str:
    """Detect the Nvidia dGPU PCI bus ID via lspci and return in PCI:bus:dev:fn format."""
    devices = _parse_gpu_devices()
    nvidia_gpus = [d for d in devices if d['vendor_id'] == _VENDOR_NVIDIA]

    if not nvidia_gpus:
        logging.error(
            "Could not find Nvidia GPU on the PCI bus. "
            "If you are switching from integrated mode, the dGPU may have been "
            "powered off by GreenWithEnvy's udev rules. To recover:\n"
            "  1. Run 'sudo greenwithenvy --reset' to remove all GreenWithEnvy config\n"
            "  2. Reboot to restore the GPU on the PCI bus\n"
            "  3. Then switch to your desired mode with 'sudo greenwithenvy -s <mode>'")
        sys.exit(1)

    if len(nvidia_gpus) > 1:
        logging.warning(
            f"Found {len(nvidia_gpus)} Nvidia GPUs, using the first one: "
            f"{nvidia_gpus[0]['description']}")

    gpu = nvidia_gpus[0]
    pci_bus_id = gpu['slot']  # format: "bus:device.function" e.g. "01:00.0"
    logging.info(f"Using Nvidia GPU: {gpu['description']} at {gpu['slot']}")

    # return BusID in 'PCI:bus:device:function' format with hex-to-decimal conversion
    bus, device_function = pci_bus_id.split(":")
    device, function = device_function.split(".")
    return f"PCI:{int(bus, 16)}:{int(device, 16)}:{int(function, 16)}"


def get_igpu_vendor() -> Optional[str]:
    """Detect the integrated GPU vendor via PCI vendor ID, skipping Nvidia devices."""
    devices = _parse_gpu_devices()

    for device in devices:
        # skip Nvidia dGPUs
        if device['vendor_id'] == _VENDOR_NVIDIA:
            continue

        vendor_name = _IGPU_VENDOR_MAP.get(device['vendor_id'])
        if vendor_name:
            logging.info(
                f"Found {vendor_name} iGPU: {device['description']} "
                f"(vendor {device['vendor_id']})")
            return vendor_name

    # fallback: log all detected vendor IDs for debugging
    vendor_ids = {d['vendor_id'] for d in devices if d['vendor_id'] != _VENDOR_NVIDIA}
    if vendor_ids:
        logging.warning(
            f"Found non-Nvidia GPU(s) with unrecognized vendor ID(s): "
            f"{', '.join(sorted(vendor_ids))}. "
            f"Please report this at https://github.com/bayasdev/greenwithenvy/issues")
    else:
        logging.warning("Could not find any integrated GPU")
    return None


def get_display_manager() -> Optional[str]:
    """Auto-detect the active display manager from systemd service config."""
    try:
        with open('/etc/systemd/system/display-manager.service', 'r', encoding='utf-8') as f:
            content = f.read()
            match = re.search(r'ExecStart=(.+)\n', content)
            if match:
                # only return the final component of the path
                display_manager = os.path.basename(match.group(1))
                logging.info(f"Found {display_manager} Display Manager")
                return display_manager
    except FileNotFoundError:
        logging.warning("Display Manager detection is not available")
    return None


def generate_xrandr_script(igpu_vendor: Optional[str]) -> str:
    """Generate an xrandr provider output source script for the given iGPU vendor."""
    if igpu_vendor == 'intel':
        return NVIDIA_XRANDR_SCRIPT.format('modesetting')
    elif igpu_vendor == 'amd':
        amd_igpu_name = get_amd_igpu_name()
        if amd_igpu_name is not None:
            return NVIDIA_XRANDR_SCRIPT.format(amd_igpu_name)
        else:
            return NVIDIA_XRANDR_SCRIPT.format('modesetting')
    else:
        return NVIDIA_XRANDR_SCRIPT.format('modesetting')


def get_amd_igpu_name() -> Optional[str]:
    """Detect the AMD iGPU provider name from xrandr output."""
    xrandr_path = shutil.which('xrandr')
    if not xrandr_path:
        logging.warning(
            "The 'xrandr' command is not available. Make sure the package is installed!")
        return None

    try:
        xrandr_output = subprocess.check_output(
            [xrandr_path, '--listproviders']).decode('utf-8')
    except subprocess.CalledProcessError:
        logging.warning(
            "Failed to run the 'xrandr' command.")
        return None

    # Match provider names containing ATI, AMD, or AMD/ATI
    pattern = re.compile(r'name:\s*((?:AMD/ATI|AMD|ATI)\S*)')

    match = pattern.search(xrandr_output)
    if match:
        name = match.group(1)
        logging.info(f"Found AMD iGPU xrandr provider: {name}")
        return name
    else:
        logging.warning(
            "Could not find AMD iGPU in 'xrandr' output.")
        return None


def rebuild_initramfs() -> None:
    """Rebuild the initramfs using the appropriate distro-specific tool."""
    # OSTree systems first
    if any(os.path.exists(dir) for dir in ['/ostree', '/sysroot/ostree']):
        command = ['rpm-ostree', 'initramfs', '--enable', '--arg=--force']

    # Detect initramfs tool by command presence (more reliable than release files)
    elif shutil.which('update-initramfs'):
        command = ['update-initramfs', '-u', '-k', 'all']
    elif shutil.which('dracut-rebuild'):
        command = ['dracut-rebuild']
    elif shutil.which('dracut'):
        command = ['dracut', '--force', '--regenerate-all']
    elif shutil.which('make-initrd'):
        command = ['make-initrd']
    elif shutil.which('mkinitcpio'):
        command = ['mkinitcpio', '-P']
    elif os.path.exists('/usr/lib/booster/regenerate_images'):
        command = ['/usr/lib/booster/regenerate_images']
    else:
        command = []
        logging.warning(
            "No supported initramfs tool found "
            "(update-initramfs, dracut, mkinitcpio, make-initrd, or booster)")

    if len(command) != 0:
        tool_name = command[0]
        if shutil.which("systemd-inhibit"):
            command = [
                'systemd-inhibit',
                '--who=greenwithenvy',
                '--why', 'Rebuilding initramfs',
                '--',
                *command
            ]

        print(f'Rebuilding the initramfs with {tool_name}...')
        returncode = _run_cmd(command)
        if returncode == 0:
            print('Successfully rebuilt the initramfs!')
        else:
            logging.warning(
                "The initramfs rebuild command exited with a non-zero status. "
                "This may be caused by missing firmware warnings rather than a "
                "real failure. Check the output above with --verbose for details.")


def create_file(path: str, content: str, executable: bool = False) -> None:
    """Write content to a file, creating parent directories as needed."""
    try:
        # create the parent folders if needed
        if not os.path.exists(os.path.dirname(path)):
            os.makedirs(os.path.dirname(path))
        with open(path, mode='w', encoding='utf-8') as f:
            f.write(content)
        logging.info(f"Created file {path}")
        if logging.getLogger().level == logging.DEBUG:
            print(content)

        # add execution privilege
        if executable:
            subprocess.run(['chmod', '+x', path], stdout=subprocess.DEVNULL)
            logging.info(f"Added execution privilege to file {path}")
    except OSError as e:
        logging.error(f"Failed to create file '{path}': {e}")


def assert_root() -> None:
    """Exit with an error if not running as root."""
    if os.geteuid() != 0:
        logging.error("This operation requires root privileges")
        sys.exit(1)


def get_current_mode() -> str:
    """Detect the current graphics mode by checking for generated config files."""
    mode = 'hybrid'
    if (os.path.exists(BLACKLIST_PATH)
            or os.path.exists(UDEV_INTEGRATED_PATH)
            or os.path.exists('/lib/udev/rules.d/50-remove-nvidia.rules')):
        mode = 'integrated'
    elif os.path.exists(XORG_PATH) and os.path.exists(MODESET_PATH):
        mode = 'nvidia'
    return mode


class CachedConfig:
    """Adapter for reading/writing the Nvidia PCI bus ID cache file."""

    def __init__(self, app_args: argparse.Namespace) -> None:
        self.app_args = app_args
        self.current_mode = get_current_mode()
        self.nvidia_gpu_pci_bus: Optional[str] = None
        self.obj: Optional[dict] = None

    @contextmanager
    def adapter(self):
        """Context manager that provides a cached PCI bus getter for graphics_mode_switcher."""
        use_cache = os.path.exists(CACHE_FILE_PATH)

        if self.is_hybrid() and getattr(self.app_args, 'switch', None) != 'hybrid':
            self.create_cache_file()  # cache GPU PCI bus when leaving hybrid

        if use_cache and not self.is_hybrid():
            self.read_cache_file()  # read existing cache when not in hybrid mode

        yield self

    def get_pci_bus_getter(self) -> Callable[[], str]:
        """Return a callable that provides the Nvidia PCI bus ID (cached or live)."""
        if self.nvidia_gpu_pci_bus is not None:
            return self._get_nvidia_gpu_pci_bus
        return get_nvidia_gpu_pci_bus

    def create_cache_file(self) -> None:
        """Create the cache file with the current Nvidia PCI bus ID. Only works in hybrid mode."""
        if not self.is_hybrid():
            raise ValueError(
                '--cache-create requires that the system be in the hybrid Optimus mode')

        self.nvidia_gpu_pci_bus = get_nvidia_gpu_pci_bus()
        self.obj = self._create_cache_obj(self.nvidia_gpu_pci_bus)
        self._write_cache_file()

    @staticmethod
    def _create_cache_obj(nvidia_gpu_pci_bus: str) -> dict:
        """Build the cache dictionary."""
        return {
            'nvidia_gpu_pci_bus': nvidia_gpu_pci_bus
        }

    def is_hybrid(self) -> bool:
        """Check if the system is currently in hybrid mode."""
        return 'hybrid' == self.current_mode

    def _get_nvidia_gpu_pci_bus(self) -> str:
        """Return the cached Nvidia PCI bus ID."""
        return self.nvidia_gpu_pci_bus

    @staticmethod
    def delete_cache_file() -> None:
        """Delete the cache file and its parent directory if they exist."""
        if os.path.exists(CACHE_FILE_PATH):
            os.remove(CACHE_FILE_PATH)
            logging.debug(f"Removed file {CACHE_FILE_PATH}")
        cache_dir = os.path.dirname(CACHE_FILE_PATH)
        if os.path.isdir(cache_dir):
            try:
                os.removedirs(cache_dir)
            except OSError:
                pass

    def read_cache_file(self) -> None:
        """Read the cache file and populate instance attributes."""
        from json import loads
        if os.path.exists(CACHE_FILE_PATH):
            with open(CACHE_FILE_PATH, 'r', encoding='utf-8') as f:
                content = f.read()
            self.obj = loads(content)
            self.nvidia_gpu_pci_bus = self.obj['nvidia_gpu_pci_bus']
        elif self.is_hybrid():
            self.nvidia_gpu_pci_bus = get_nvidia_gpu_pci_bus()
        else:
            raise ValueError(
                'No cache present. Operation requires that the system be in the hybrid Optimus mode')

    @staticmethod
    def show_cache_file() -> None:
        """Print the contents of the cache file, or an error message if it doesn't exist."""
        content = f'ERROR: Could not read {CACHE_FILE_PATH}'
        if os.path.exists(CACHE_FILE_PATH):
            with open(CACHE_FILE_PATH, 'r', encoding='utf-8') as f:
                content = f.read()
        print(content)

    def _write_cache_file(self) -> None:
        """Write the cache object to disk as JSON."""
        from json import dump
        os.makedirs(os.path.dirname(CACHE_FILE_PATH), exist_ok=True)

        with open(CACHE_FILE_PATH, 'w', encoding='utf-8') as f:
            dump(self.obj, fp=f, indent=4, sort_keys=False)

        logging.debug(f"Created file {CACHE_FILE_PATH}")


def main() -> None:
    """Entry point: parse CLI arguments and dispatch to the appropriate action."""
    # define CLI arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--version', action='version', version=VERSION,
                        help='Output the current version')
    parser.add_argument('-q', '--query', action='store_true',
                        help='Query the current graphics mode')
    parser.add_argument('-s', '--switch', type=str, metavar='MODE', action='store', choices=SUPPORTED_MODES,
                        help='Switch the graphics mode. Available choices: %(choices)s')
    parser.add_argument('--dm', type=str, metavar='DISPLAY_MANAGER', action='store', choices=SUPPORTED_DISPLAY_MANAGERS,
                        help='Manually specify your Display Manager for Nvidia mode. Available choices: %(choices)s')
    parser.add_argument('--force-comp', action='store_true',
                        help='Enable ForceCompositionPipeline on Nvidia mode')
    parser.add_argument('--coolbits', type=int, nargs='?', metavar='VALUE', action='store', const=28,
                        help='Enable Coolbits on Nvidia mode. Default if specified: %(const)s')
    parser.add_argument('--rtd3', type=int, nargs='?', metavar='VALUE', action='store', choices=RTD3_MODES, const=2,
                        help='Setup PCI-Express Runtime D3 (RTD3) Power Management on Hybrid mode. Available choices: %(choices)s. Default if specified: %(const)s')
    parser.add_argument('--use-nvidia-current', action='store_true',
                        help='Use nvidia-current instead of nvidia for kernel modules')
    parser.add_argument('--reset-sddm', action='store_true',
                        help='Restore default Xsetup file')
    parser.add_argument('--reset', action='store_true',
                        help='Revert changes made by GreenWithEnvy')
    parser.add_argument('--cache-create', action='store_true',
                        help='Create cache used by GreenWithEnvy; only works in hybrid mode')
    parser.add_argument('--cache-delete', action='store_true',
                        help='Delete cache created by GreenWithEnvy')
    parser.add_argument('--cache-query', action='store_true',
                        help='Show cache created by GreenWithEnvy')
    parser.add_argument('--verbose', default=False, action='store_true',
                        help='Enable verbose mode')

    # print help if no arg is provided
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)

    args = parser.parse_args()

    # log formatting
    logging.basicConfig(format='%(levelname)s: %(message)s')

    # set debug level for verbose mode
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.query:
        mode = get_current_mode()
        print(mode)
        return
    elif args.cache_create:
        assert_root()
        CachedConfig(args).create_cache_file()
        return
    elif args.cache_delete:
        assert_root()
        CachedConfig.delete_cache_file()
        return
    elif args.cache_query:
        CachedConfig.show_cache_file()
        return

    if args.switch or args.reset_sddm or args.reset:
        with CachedConfig(args).adapter() as cached_config:
            if args.switch:
                assert_root()
                graphics_mode_switcher(
                    args.switch, args.dm,
                    args.force_comp, args.coolbits, args.rtd3,
                    args.use_nvidia_current,
                    pci_bus_getter=cached_config.get_pci_bus_getter(),
                )
            elif args.reset_sddm:
                assert_root()
                create_file(SDDM_XSETUP_PATH, SDDM_XSETUP_CONTENT, True)
                print('Operation completed successfully')
            elif args.reset:
                assert_root()
                cleanup()
                CachedConfig.delete_cache_file()
                rebuild_initramfs()
                print('Operation completed successfully')


if __name__ == '__main__':
    main()
